/turtle_mover:
  ros__parameters:
    catch_closest_turtle_first: True
    linear_gain: 2.0
    angular_gain: 5.0
    distance_tolerance: 0.4

/turtle_spawner:
  ros__parameters:
    spawn_frequency: 1.0
    turtle_name_prefix: spawned_turtle
